### PR TITLE
Work with gitignore

### PR DESCRIPTION
**Pull request by chiemeliecoder**
Please review my code

### CODE REVIEW

**Review by TomashevskiiVladimirSolvd — APPROVED** [review]
Looks good

**Review by kabuki-mono — APPROVED** [review]
LGTM

**Review by remynewton — CHANGES_REQUESTED** [review]
1. Use log4j logger instead of printStackTrace(), throw new exceptions, or println statements.
2. Should we be initializing (i.e. MyBatisInitializer.initialize()) for every single query? Or should we just use a static block for the initialization?

**Review by chiemeliecoder — COMMENTED** [review]
looks good

**Review by remynewton — APPROVED** [review]

**Pull request merged**
