### PR TITLE
First Pull Request for Training purpose

### PR DESCRIPTION
**Pull request by TomashevskiiVladimirSolvd**

### CODE REVIEW

**Comment by TomashevskiiVladimirSolvd** [comment]
change gitignore

**Review by remynewton — APPROVED** [review]

**Review by remynewton — APPROVED** [review]

**Review by remynewton — COMMENTED** [review]
I don't see a change here?

**Comment by TomashevskiiVladimirSolvd** [comment]
> I don't see a change here?

i just added resource folder and created java class Point without any code .Just for practicing Pull request purpose.

**Comment by chiemeliecoder** [comment]
Looks good

**Pull request closed without merging**
